### ISSUE TITLE
DragonBones Extension on OSX

### ISSUE THREAD

**Issue by Lykdraft** [Daylily-Zeleen/Godot-DragonBones#16]
Hey there!

I've seen today this error on OSX 10.14.6:

```
--- Debugging process stopped ---
  Can't open dynamic library: /Volumes/HDD2/LK/godotdbe/addons/gddragonbones/bin/libgddragonbones.macos.template_debug.framework. 
Error: dlopen(/Volumes/HDD2/LK/godotdbe/addons/gddragonbones/bin/libgddragonbones.macos.template_debug.framework/libgddragonbones.macos.template_debug, 
2): Symbol not found: __ZTTNSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE

Referenced from: /Volumes/HDD2/LK/godotdbe/addons/gddragonbones/bin/libgddragonbones.macos.template_debug.framework/libgddragonbones.macos.template_debug 
**(which was built for Mac OS X 14.0)**
```
Aha, I thought... Build for OSX 14.0. That's a bit of a high system requirement.
So I thought I give it a shot and compile it myself for at least OSX Mojave.
But when I tried, I had this output:

```
TypeError: 'type' object is not subscriptable:
  File "/Volumes/HDD2/Luetze/Downloads/New Folder With Items 3/Godot-DragonBones-master/SConstruct", line 28:
    def add_sources_recursively(dir: str, glob_sources, exclude_folder: list[str] = []):
```
Hmm. I have no idea how to tackle this one... Maybe you can help?

That is the Folder Structure, I think this is right (I had to manually download and rename the Godot cpp git...) so maybe
there is an error in the structure..?

![Screenshot 2024-06-09 at 17 31 59](https://github.com/Daylily-Zeleen/Godot-DragonBones/assets/18437561/dc041c12-3165-432a-8d50-08299da32bda)

Best,
tL.

**Comment by Daylily-Zeleen** [comment]
It looks like a script syntax or runtime error.

It seems that the type hint `list[str]` is be recognized as a subscript expression (not sure).
You can remove type hints in "SConstruct" and try to build again.

**Comment by Lykdraft** [comment]
Thank you, good idea. It worked, but  then I got **tons** of errors when compiling:

ex.1:
```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_intptr_t.h:30:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
**#error architecture not supported**
```

ex.2:

```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdint.h:53:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_intptr_t.h:32:9: error: unknown type name '__darwin_intptr_t'
typedef __darwin_intptr_t       intptr_t;
```

ex.3:

```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdint.h:52:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_dev_t;         /* dev_t */
```
ex.4:

```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'; did you mean 'uint64_t'?
typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types/_uint64_t.h:31:28: note: 'uint64_t' declared here
typedef unsigned long long uint64_t;
                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

Maybe this is because my XCode Commandline Tools are pretty old (because I am still with my Mac on Mojave, clang 11.x I think...) I'll check this evening to make sure if that's the case.

**Comment by Daylily-Zeleen** [comment]
You can try to refer the [build.yml](https://github.com/Daylily-Zeleen/Godot-DragonBones/blob/74904f3515b4b244f7c5a2eaa9ac84b3981e97b3/.github/workflows/build.yml) to check requirements of macos build (such as runner system, python version, build commands and so on).
Although it can not work properly, it has indeed been compiled successfully.

**Comment by Lykdraft** [comment]
Well, it says:
```
- identifier: macos-universal-release
                      name: 🍎 macOS (universal) Release
                      runner: macos-latest
                      target: template_release
                      platform: macos
                      arch: universal
```
I forgot what "Univeral" means. Probably compiling to two architectures. But runner is: `latest` so that's not so good...
I've seen that the very first error on the bottom showed `build with OSX 14.0` 
I think there's not much I can do now from my side. Do you have another idea what I could do?

**Comment by Daylily-Zeleen** [comment]
To be honest, I'm not familiar with macos, osx, xcode and so on. I can just do more test about macos building on the github action.

I push a [new branch](https://github.com/Daylily-Zeleen/Godot-DragonBones/tree/macos_building_test) to test macos building on `macos-latest` and `macos-12`, and building for different architectures (universal, arm64 and x86_64).
You can see all [jobs](https://github.com/Daylily-Zeleen/Godot-DragonBones/actions/runs/9438093388) are working fine.

**Comment by Daylily-Zeleen** [comment]
Additionally, you have mentioned that your toolchain is pretty old.

I have meet similar issue about android building, the ndk is too old and its c++20 features are mark as experimental, so I update ndk to solve this problem.

In other words, the godot-cpp is require c++17, perhaps your toolchain does not support c++17?

**Comment by Daylily-Zeleen** [comment]
Recomend to refer [official document](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_macos.html) for more details about compiling for macos.

**Comment by Lykdraft** [comment]
> In other words, the godot-cpp is require c++17, perhaps your toolchain does not support c++17?

No, indeed it doesn't... Bummer. Anyway, thanks for your help.
